2022-08-19 07:31:15
Available GPU List
id	utilization.gpu(%)	memory.free(MiB)
0 	0                 	32510           
1 	0                 	32510           
2 	0                 	32510           
3 	0                 	32510           
4 	0                 	32510           
5 	0                 	32510           
6 	0                 	32510           
7 	1                 	32510           
Select id #0, 1, 2, 3, 4, 5, 6, 7 for you.
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Number of train data: 310578
Number of val data: 34341
Number of test data: 104206
number of parameters :  261567
Let's use 8 GPUs!
Process Process-3:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-1:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-8:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-2:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-6:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-4:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-7:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
Process Process-5:
Traceback (most recent call last):
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/caoduanhua/anaconda3/envs/prolif/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 202, in run
    model,train_losses,optimizer,scheduler = train(model,args,optimizer,loss_fn,train_dataloader,auxiliary_loss,scheduler)
  File "/home/caoduanhua/score_function/GNN/GNN_graphformer_pyg/utils.py", line 359, in train
    print('time load data:',time_batch - start)
UnboundLocalError: local variable 'start' referenced before assignment
